services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: dms-mail
    hostname: mail.m.cargoffer.com
    restart: unless-stopped
    ports:
      - "25:25"
      - "110:110"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
    expose:
      - "8080"
    volumes:
      - /opt/mailu/mail-data:/var/mail
      - /opt/mailu/mail-state:/var/mail-state
      - /opt/mailu/mail-logs:/var/log/mail
      - /opt/mailu/config:/tmp/docker-mailserver
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_RSPAMD=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=0
      - SSL_TYPE=self-signed
      - PERMIT_DOCKER=none
      - ONE_DIR=1
      - SPOOF_PROTECTION=1
      - ENABLE_POP3=1
      - SMTP_ONLY=0
    labels:
      - traefik.enable=true
      - traefik.http.routers.mailu-front.rule=Host(`mail.m.cargoffer.com`)
      - traefik.http.routers.mailu-front.entryPoints=https
      - traefik.http.routers.mailu-front.tls.certresolver=letsencrypt
      - traefik.http.services.mailu-front.loadbalancer.server.port=8080
    networks:
      - jhv4mlu5xo3fbhtinziuuggf

networks:
  jhv4mlu5xo3fbhtinziuuggf:
    external: true
